apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: nginx
        ports:
          - containerPort: 80

        resources:
            requests:
              cpu: "100m"     # 100 millicores (1/10th of a CPU core)
              memory: "128Mi"
            limits:
              cpu: "250m"     # Maximum 1/4th of a core
              memory: "256Mi"
