apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:

      initContainers: 
      - name: frontend-init-container
        image: alpine 
        command: ["sh", "-c"]
      
        args: ['wget -O /repo/index.html https://raw.githubusercontent.com/AbdelrahmanElhelw/k8s-phishing-project/main/phishing-directory/frontend/html/index.html']
        volumeMounts:
        - name: shared-html
          mountPath: /repo

      containers:
      - name: frontend-container
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: shared-html          
            mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: "100m"     # 100 millicores (1/10th of a CPU core)
            memory: "128Mi"
          limits:
            cpu: "250m"     # Maximum 1/4th of a core
            memory: "256Mi"
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "phishing"
        effect: "NoSchedule"

      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "project"
                operator: "In"
                values:
                - "phishing"
                
      volumes:
      - name: shared-html
        emptyDir: {}
