apiVersion: apps/v1
kind: StatefulSet                
metadata:
  name: stateful-database        
spec:
  serviceName: "database-service" 
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret          
                  key: mysql-root-password    

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:  
                  name: project-cm
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mysql-secret
                  key: DB_PASSWORD  
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:  
                  name: project-cm
                  key: DB_NAME
            

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql  # This is the default path where MySQL saves data

      tolerations:
      - key: "project"
        operator: "Equal"
        value: "phishing"
        effect: "NoSchedule"

      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "project"
                operator: "In"
                values:
                - "phishing" 
                
    volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi   # Asking for 1 GB of storage

